
create extension if not exists pgcrypto;

create table if not exists public.teams(
  id uuid primary key default gen_random_uuid(),
  name text not null check(length(btrim(name)) between 1 and 120),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members(
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  primary key(team_id,user_id)
);

create table if not exists public.people(
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  name text not null check(length(btrim(name)) between 1 and 160),
  identifier text,
  photo_url text,
  photo_path text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_dates(
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  date date not null,
  created_at timestamptz not null default now(),
  unique(team_id,date)
);

create table if not exists public.attendance(
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  person_id uuid not null references public.people(id) on delete cascade,
  date date not null,
  status text not null check(status in ('present','absent')),
  marked_by uuid references auth.users(id) on delete set null,
  marked_at timestamptz not null default now(),
  unique(team_id,person_id,date)
);

create table if not exists public.audit_events(
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists people_team_idx on public.people(team_id);
create index if not exists people_team_active_idx on public.people(team_id,active,name);
create unique index if not exists people_team_identifier_unique
  on public.people(team_id,identifier)
  where identifier is not null and length(btrim(identifier)) > 0;
create index if not exists dates_team_idx on public.attendance_dates(team_id,date);
create index if not exists attendance_team_date_idx on public.attendance(team_id,date);
create index if not exists attendance_person_idx on public.attendance(person_id,date);
create index if not exists audit_team_created_idx on public.audit_events(team_id,created_at desc);

alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.people enable row level security;
alter table public.attendance_dates enable row level security;
alter table public.attendance enable row level security;
alter table public.audit_events enable row level security;

create or replace function public.is_team_member(tid uuid)
returns boolean
language sql stable security definer
set search_path=public
as $$
  select exists(
    select 1 from public.team_members
    where team_id=tid and user_id=auth.uid()
  );
$$;

create or replace function public.is_team_admin(tid uuid)
returns boolean
language sql stable security definer
set search_path=public
as $$
  select exists(
    select 1 from public.team_members
    where team_id=tid and user_id=auth.uid() and role in ('owner','admin')
  );
$$;

create or replace function public.create_team(p_name text)
returns public.teams
language plpgsql
security definer
set search_path=public
as $$
declare
  t public.teams;
  clean_name text := nullif(btrim(p_name),'');
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if clean_name is null then
    clean_name := 'My Team';
  end if;
  if length(clean_name) > 120 then
    raise exception 'Team name is too long';
  end if;

  insert into public.teams(name,created_by)
  values(clean_name,auth.uid())
  returning * into t;

  insert into public.team_members(team_id,user_id,role)
  values(t.id,auth.uid(),'owner');

  return t;
end;
$$;

grant execute on function public.create_team(text) to authenticated;

create or replace function public.protect_team_scope()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='UPDATE' and new.team_id is distinct from old.team_id then
    raise exception 'Team ownership cannot be changed from the client';
  end if;
  return new;
end;
$$;

create or replace function public.validate_attendance_team()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(
    select 1 from public.people
    where id=new.person_id and team_id=new.team_id
  ) then
    raise exception 'Attendance person does not belong to this team';
  end if;
  return new;
end;
$$;

create or replace function public.touch_attendance()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  new.marked_at := now();
  return new;
end;
$$;

create or replace function public.delete_attendance_for_date()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  delete from public.attendance
  where team_id=old.team_id and date=old.date;
  return old;
end;
$$;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  tid uuid;
  eid uuid;
  payload jsonb;
begin
  if tg_op='DELETE' then
    tid := old.team_id;
    eid := old.id;
    payload := to_jsonb(old);
  else
    tid := new.team_id;
    eid := new.id;
    payload := to_jsonb(new);
  end if;

  insert into public.audit_events(
    team_id,actor_user_id,action,entity,entity_id,details
  )
  values(
    tid,auth.uid(),tg_op,tg_table_name,eid,payload
  );

  if tg_op='DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists people_protect_team on public.people;
create trigger people_protect_team
before update on public.people
for each row execute function public.protect_team_scope();

drop trigger if exists dates_protect_team on public.attendance_dates;
create trigger dates_protect_team
before update on public.attendance_dates
for each row execute function public.protect_team_scope();

drop trigger if exists attendance_protect_team on public.attendance;
create trigger attendance_protect_team
before update on public.attendance
for each row execute function public.protect_team_scope();

drop trigger if exists attendance_validate_team on public.attendance;
create trigger attendance_validate_team
before insert or update on public.attendance
for each row execute function public.validate_attendance_team();

drop trigger if exists attendance_touch_marked_at on public.attendance;
create trigger attendance_touch_marked_at
before insert or update on public.attendance
for each row execute function public.touch_attendance();

drop trigger if exists attendance_dates_cleanup on public.attendance_dates;
create trigger attendance_dates_cleanup
after delete on public.attendance_dates
for each row execute function public.delete_attendance_for_date();

drop trigger if exists audit_people on public.people;
create trigger audit_people
after insert or update or delete on public.people
for each row execute function public.audit_row_change();

drop trigger if exists audit_dates on public.attendance_dates;
create trigger audit_dates
after insert or update or delete on public.attendance_dates
for each row execute function public.audit_row_change();

drop trigger if exists audit_attendance on public.attendance;
create trigger audit_attendance
after insert or update or delete on public.attendance
for each row execute function public.audit_row_change();

drop policy if exists "members read teams" on public.teams;
drop policy if exists "users create teams" on public.teams;
drop policy if exists "admins update teams" on public.teams;
create policy "members read teams" on public.teams
  for select using(public.is_team_member(id) or created_by=auth.uid());
create policy "users create teams" on public.teams
  for insert with check(created_by=auth.uid());
create policy "admins update teams" on public.teams
  for update using(public.is_team_admin(id)) with check(public.is_team_admin(id));

drop policy if exists "members read team membership" on public.team_members;
drop policy if exists "users join created team" on public.team_members;
drop policy if exists "admins manage membership" on public.team_members;
drop policy if exists "admins remove membership" on public.team_members;
create policy "members read team membership" on public.team_members
  for select using(user_id=auth.uid() or public.is_team_admin(team_id));
create policy "users join created team" on public.team_members
  for insert with check(user_id=auth.uid() and exists(
    select 1 from public.teams where id=team_id and created_by=auth.uid()
  ));
create policy "admins manage membership" on public.team_members
  for update using(public.is_team_admin(team_id))
  with check(public.is_team_admin(team_id));
create policy "admins remove membership" on public.team_members
  for delete using(public.is_team_admin(team_id) or user_id=auth.uid());

drop policy if exists "members read people" on public.people;
drop policy if exists "members add people" on public.people;
drop policy if exists "members update people" on public.people;
drop policy if exists "admins delete people" on public.people;
create policy "members read people" on public.people
  for select using(public.is_team_member(team_id));
create policy "members add people" on public.people
  for insert with check(public.is_team_member(team_id));
create policy "members update people" on public.people
  for update using(public.is_team_member(team_id))
  with check(public.is_team_member(team_id));
create policy "admins delete people" on public.people
  for delete using(public.is_team_admin(team_id));

drop policy if exists "members read dates" on public.attendance_dates;
drop policy if exists "members add dates" on public.attendance_dates;
drop policy if exists "admins delete dates" on public.attendance_dates;
create policy "members read dates" on public.attendance_dates
  for select using(public.is_team_member(team_id));
create policy "members add dates" on public.attendance_dates
  for insert with check(public.is_team_member(team_id));
create policy "admins delete dates" on public.attendance_dates
  for delete using(public.is_team_admin(team_id));

drop policy if exists "members read attendance" on public.attendance;
drop policy if exists "members insert attendance" on public.attendance;
drop policy if exists "members update attendance" on public.attendance;
drop policy if exists "members delete attendance" on public.attendance;
create policy "members read attendance" on public.attendance
  for select using(public.is_team_member(team_id));
create policy "members insert attendance" on public.attendance
  for insert with check(public.is_team_member(team_id) and marked_by=auth.uid());
create policy "members update attendance" on public.attendance
  for update using(public.is_team_member(team_id))
  with check(public.is_team_member(team_id) and marked_by=auth.uid());
create policy "members delete attendance" on public.attendance
  for delete using(public.is_team_member(team_id));

drop policy if exists "admins read audit" on public.audit_events;
create policy "admins read audit" on public.audit_events
  for select using(public.is_team_admin(team_id));

insert into storage.buckets(id,name,public)
values('avatars','avatars',false)
on conflict(id) do nothing;

update storage.buckets set public=false where id='avatars';

drop policy if exists "members upload avatar" on storage.objects;
drop policy if exists "members update avatar" on storage.objects;
drop policy if exists "members delete avatar" on storage.objects;
drop policy if exists "members read avatar" on storage.objects;

create policy "members read avatar" on storage.objects
  for select to authenticated
  using(
    bucket_id='avatars'
    and public.is_team_member((storage.foldername(name))[1]::uuid)
  );

create policy "members upload avatar" on storage.objects
  for insert to authenticated
  with check(
    bucket_id='avatars'
    and public.is_team_member((storage.foldername(name))[1]::uuid)
  );

create policy "members update avatar" on storage.objects
  for update to authenticated
  using(
    bucket_id='avatars'
    and public.is_team_member((storage.foldername(name))[1]::uuid)
  )
  with check(
    bucket_id='avatars'
    and public.is_team_member((storage.foldername(name))[1]::uuid)
  );

create policy "members delete avatar" on storage.objects
  for delete to authenticated
  using(
    bucket_id='avatars'
    and public.is_team_member((storage.foldername(name))[1]::uuid)
  );

do $$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='people'
  ) then
    execute 'alter publication supabase_realtime add table public.people';
  end if;

  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='attendance_dates'
  ) then
    execute 'alter publication supabase_realtime add table public.attendance_dates';
  end if;

  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='attendance'
  ) then
    execute 'alter publication supabase_realtime add table public.attendance';
  end if;
end $$;
