-- ============================================================
-- TEST-ONLY: test users, test bookkeeping tables, and helper
-- functions used by behavior_tests.sql. Run as postgres.
-- ============================================================

insert into auth.users(id,email) values
  ('11111111-1111-1111-1111-111111111111','owner-a@test.dev'),
  ('22222222-2222-2222-2222-222222222222','member-b@test.dev'),
  ('33333333-3333-3333-3333-333333333333','owner-c@test.dev')
on conflict (id) do nothing;

grant usage on schema storage to authenticated, anon;
grant select on storage.buckets to authenticated, anon;
grant all on storage.objects to authenticated, anon;
grant usage on schema auth to authenticated;
grant execute on function auth.uid() to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create table if not exists public.test_results(
  id bigint generated by default as identity primary key,
  name text not null,
  passed boolean not null,
  note text
);
grant all on public.test_results to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Record a named assertion result.
create or replace function public.report_test(p_name text, p_passed boolean, p_note text)
returns void
language plpgsql
as $$
begin
  insert into public.test_results(name,passed,note)
  values(p_name,p_passed,p_note);
end $$;
grant execute on function public.report_test(text,boolean,text) to authenticated;

-- Run a SQL statement, swallow its error, and return the message
-- (null when the statement succeeds). Executes with invoker rights,
-- so RLS and policies apply as usual.
create or replace function public.expect_error(p_sql text)
returns text
language plpgsql
as $$
begin
  execute p_sql;
  return null;
exception when others then
  return sqlerrm;
end $$;
grant execute on function public.expect_error(text) to authenticated;
